stages:
  - test
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

# Executa testes Python
test:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest tests/ --cov=app/ --cov-report=xml
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - coverage.xml
  only:
    - merge_requests
    - main

# Constrói a imagem Docker
build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker build -t $IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
  only:
    - main